version: '3.8'
services:
  redis-server:
    hostname: redis
    image: 'redis'
    ports:
      - "6379:6379"
  petclinic:
    build:
      context: .
      target: development
    links:
      - redis-server
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST= cache
      - SPRING_REDIS_PORT= 6379
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
  mysqlserver:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

  nginx:
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_CONF=events {} http { server { listen 80; location / { proxy_pass http://petclinic:8080; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $scheme; } } }
    depends_on:
      - petclinic
volumes:
  mysql_data:
  mysql_config: